# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matern_5_2_funct <- function(d, beta_i) {
    .Call('RobustGaSP_matern_5_2_funct', PACKAGE = 'RobustGaSP', d, beta_i)
}

matern_3_2_funct <- function(d, beta_i) {
    .Call('RobustGaSP_matern_3_2_funct', PACKAGE = 'RobustGaSP', d, beta_i)
}

pow_exp_funct <- function(d, beta_i, alpha_i) {
    .Call('RobustGaSP_pow_exp_funct', PACKAGE = 'RobustGaSP', d, beta_i, alpha_i)
}

matern_5_2_deriv <- function(R0_i, R, beta_i) {
    .Call('RobustGaSP_matern_5_2_deriv', PACKAGE = 'RobustGaSP', R0_i, R, beta_i)
}

matern_3_2_deriv <- function(R0_i, R, beta_i) {
    .Call('RobustGaSP_matern_3_2_deriv', PACKAGE = 'RobustGaSP', R0_i, R, beta_i)
}

pow_exp_deriv <- function(R0_i, R, beta_i, alpha_i) {
    .Call('RobustGaSP_pow_exp_deriv', PACKAGE = 'RobustGaSP', R0_i, R, beta_i, alpha_i)
}

separable_kernel <- function(R0, beta, kernel_type, alpha) {
    .Call('RobustGaSP_separable_kernel', PACKAGE = 'RobustGaSP', R0, beta, kernel_type, alpha)
}

log_marginal_lik <- function(param, nugget, nugget_est, R0, X, output, kernel_type, alpha) {
    .Call('RobustGaSP_log_marginal_lik', PACKAGE = 'RobustGaSP', param, nugget, nugget_est, R0, X, output, kernel_type, alpha)
}

log_approx_ref_prior <- function(param, nugget, nugget_est, CL, a, b) {
    .Call('RobustGaSP_log_approx_ref_prior', PACKAGE = 'RobustGaSP', param, nugget, nugget_est, CL, a, b)
}

log_marginal_lik_deriv <- function(param, nugget, nugget_est, R0, X, output, kernel_type, alpha) {
    .Call('RobustGaSP_log_marginal_lik_deriv', PACKAGE = 'RobustGaSP', param, nugget, nugget_est, R0, X, output, kernel_type, alpha)
}

log_approx_ref_prior_deriv <- function(param, nugget, nugget_est, CL, a, b) {
    .Call('RobustGaSP_log_approx_ref_prior_deriv', PACKAGE = 'RobustGaSP', param, nugget, nugget_est, CL, a, b)
}

log_ref_marginal_post <- function(param, nugget, nugget_est, R0, X, output, kernel_type, alpha) {
    .Call('RobustGaSP_log_ref_marginal_post', PACKAGE = 'RobustGaSP', param, nugget, nugget_est, R0, X, output, kernel_type, alpha)
}

construct_rgasp <- function(beta, nu, R0, X, output, kernel_type, alpha) {
    .Call('RobustGaSP_construct_rgasp', PACKAGE = 'RobustGaSP', beta, nu, R0, X, output, kernel_type, alpha)
}

pred_rgasp <- function(beta, nu, input, X, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, qt_025, qt_975, r0, kernel_type, alpha) {
    .Call('RobustGaSP_pred_rgasp', PACKAGE = 'RobustGaSP', beta, nu, input, X, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, qt_025, qt_975, r0, kernel_type, alpha)
}

generate_predictive_mean_cov <- function(beta, nu, input, X, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, rr0, r0, kernel_type, alpha) {
    .Call('RobustGaSP_generate_predictive_mean_cov', PACKAGE = 'RobustGaSP', beta, nu, input, X, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, rr0, r0, kernel_type, alpha)
}

